### PR TITLE
Support values of inner docs given as AttrDict instances

### LINKED ISSUE #3075: Object._serialize() missing 1 required positional argument: 'skip_empty'
This started happening with the `9.1.1` release:

```
src/catalog/search/documents.py:59: in save
    return super().save(**kwargs)
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/_sync/document.py:440: in save
    body=self.to_dict(skip_empty=skip_empty),
src/catalog/search/documents.py:79: in to_dict
    doc = super().to_dict(skip_empty=skip_empty)
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/document_base.py:593: in to_dict
    d = super().to_dict(skip_empty=skip_empty)
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/utils.py:606: in to_dict
    v = f.serialize(v, skip_empty=skip_empty)
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/field.py:152: in serialize
    return self._safe_serialize(data, skip_empty)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = Object(), data = {'data': {'abc': 'def'}}, skip_empty = True
    def _safe_serialize(self, data: Any, skip_empty: bool) -> Any:
        try:
            return self._serialize(data, skip_empty)
        except TypeError:
            # older method signature, without skip_empty
>           return self._serialize(data)  # type: ignore[call-arg]
E           TypeError: Object._serialize() missing 1 required positional argument: 'skip_empty'
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/field.py:130: TypeError
```

Everything works fine with `9.1.0`

Thanks.

### PR DESCRIPTION
**Pull request by miguelgrinberg**
Fixes #3075.

It appears that some users pass `AttrDict` instances as values for fields of type `Object` or `Nested`. If the document is validated (the default when `save()` is called) then these are handled well, but some users also call `save(validate=False)` or just `to_dict()`, in which case the AttrDicts cause the error described in #3075. This change adds logic that tolerates AttrDict values, and treats them like regular dicts (which are already tolerated).

### CODE REVIEW

File: elasticsearch/dsl/field.py [hunk 1]
```diff
@@ -572,7 +572,11 @@ def _serialize(
         if isinstance(data, collections.abc.Mapping):
             return data
 
-        return data.to_dict(skip_empty=skip_empty)
+        try:
```
Comment (leameow) [inline elasticsearch/dsl/field.py:575]: Why not just `isinstance(data, AttrDict)`?

Comment (miguelgrinberg) [reply elasticsearch/dsl/field.py:575]: Because this would also include support for other types that are not AttrDict. And because it avoids evaluating the conditional for every field that is saved, so it should perform a bit better.

Comment (leameow) [reply elasticsearch/dsl/field.py:575]: > Because this would also include support for other types that are not AttrDict.

Which would probably lead to more crash anyway?

>And because it avoids evaluating the conditional for every field that is saved, so it should perform a bit better.

Handling an exception will cost many time what an `isinstance` cost. But does a few nano seconds performance of this even matter here 🤔 Just seems an unneeded "complex" structure flow to hide a very simple intent.

Comment (miguelgrinberg) [reply elasticsearch/dsl/field.py:575]: The exception would be handled only for the fields that have a wrong type. The conditional would have to be evaluated for every single field.

Comment (leameow) [reply elasticsearch/dsl/field.py:575]: And to my point, does it even matter in this case? Elasticsearch-dsl serialization/deserialization code is clearly not designed with performance in mind, so I don't really see why this one `isinstance` is seen as a potential issue at the cost of readability. But that's just my 2 cents. (and my last comment on this :) )

**Comment by miguelgrinberg** [comment]
@isra17 Thanks for the discussion and the insights you provided.

I'm going to do some additional testing, and if you don't mind, I'm also going to bring the unit test that you created in your PR, which is different than mine.

As far as the exception vs. no exception method for preventing this error it's really not a big deal, but I have seen other methods that do an instance check like you suggested, so maybe that wins in terms of consistency. But I'm not sure if that is enough. I don't know yet if we need a similar fix for `AttrList` instances in `Nested` fields, which inherit from `Object` and use the same serialize/deserialize logic.

**Comment by leameow** [comment]
> @isra17 Thanks for the discussion and the insights you provided.

Thanks for looking at the issue! I understand this is a bit of a niche error, so it's nice to see it fixed :)

> I'm going to do some additional testing, and if you don't mind, I'm also going to bring the unit test that you created in your PR, which is different than mine.

Of course!

> I don't know yet if we need a similar fix for `AttrList` instances in `Nested` fields, which inherit from `Object` and use the same serialize/deserialize logic.

For what it's worth, I think if `AttrList` would have been an issue we would have seen it in the past since the `[de]serialize` method never dealt with list? Isn't any fields can be a list anyway? My guess is that `to_dict` on the document take care of unrolling list? Seems like `AttrDict.to_dict` does, but I can't find how `DocumentBase` does it 🤔

**Comment by leameow** [comment]
Ha, `Field.serialize` deals with the lists.

File: elasticsearch/dsl/field.py (hunk 1 above)
Comment (leameow) [reply elasticsearch/dsl/field.py:575]: Actually, fwiw, I suppose your method is consistent with [`Field._safe_serialize`](https://github.com/elastic/elasticsearch-py/pull/3041/files#diff-df682b3a1072c61688b2c15ddb0e7fbb9e64f8096f875d41e08cd2821a1da48bR125)
