### PR TITLE
[DOCS] Clarify upgrades and edit generally

### PR DESCRIPTION
**Pull request by marciw**
👁️ **Preview** [docs/reference/index.md](https://docs-v3-preview.elastic.dev/elastic/elasticsearch-py/pull/3138/reference)

## Summary of changes
- Revised the "Major version upgrades" section in response to https://github.com/elastic/docs-content-internal/issues/421
- Clarified forward compatibility
- Added phrasing and table from .NET docs + made the table more accessible
- Added links to related docs
- Did a general edit for clarity, concision, Elastic style

## ❗ Notes for reviewers
- I'll apply similar changes to the other client docs. This one will serve as the template for updating the others.
- I tried to align this with both the [.NET docs](https://www.elastic.co/docs/reference/elasticsearch/clients/dotnet#_es_version_compatibility) and https://github.com/elastic/devtools-team/pull/936/ (will iterate more when moving the latter to docs-content)

### TODO
- [x] Compare to .NET changes; go with the best of both worlds
- [x] Tweak section heading?
- [ ] ~~Clarify "outages" (whether clients need hot-swapping during major upgrades) per https://github.com/elastic/docs-content/pull/3398#issuecomment-3423887315~~ <-- will do this in a follow-up issue; going to merge this in its current state as a "phase 1" edit

### CODE REVIEW

File: docs/reference/index.md [hunk 1]
```diff
@@ -1,17 +1,18 @@
...
   - https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/overview.html
 ---
 
-# Python [overview]
+# {{es}} Python client [overview]
 
-This is the official Python client for {{es}}. Its goal is to provide common ground for all {{es}}-related code in Python. For this reason, the client is designed to be unopinionated and extendable. API reference documentation for this client is available on [Read the Docs](https://elasticsearch-py.readthedocs.io).
+This documentation covers the [official Python client for {{es}}](https://github.com/elastic/elasticsearch-py). The goal of the Python client is to provide common ground for all {{es}}-related code in Python. The client is designed to be unopinionated and extendable. 
 
+API reference documentation is provided on [Read the Docs](https://elasticsearch-py.readthedocs.io).
```
Comment (miguelgrinberg) [inline docs/reference/index.md:12]: @marciw I'm not sure when is the right time to have this discussion, but we should explore the possibility of including the reference docs here as well.

File: docs/reference/index.md [hunk 2]
```diff
@@ -46,37 +45,41 @@ The client’s features include:
...
+For example, if you're upgrading {{es}} 8.x to {{es}} 9.x, you can continue to use the 8.x Python {{es}} client during and after the server upgrade, with the exception of [breaking changes](../release-notes/breaking-changes.md).
 
-If you need to work with multiple client versions, note that older versions are also released with the `elasticsearch8` and `elasticsearch9` package names so that they can be installed together.
+To enable compatibility mode, set the environment variable `ELASTIC_CLIENT_APIVERSIONING` to `true`. For more details, refer to [{{es}} API compatibility](elasticsearch://reference/elasticsearch/rest-apis/compatibility.md).
```
Comment (miguelgrinberg) [inline docs/reference/index.md]: The Python client does not implement this environment variable. Compatibility mode is always enabled.

Comment (marciw) [reply docs/reference/index.md]: whoops, thank you!

File: docs/reference/index.md (hunk 1 above)
Comment (marciw) [reply docs/reference/index.md:12]: yes! This can probably be part of some other cleanup we're doing, so added it to the list here: https://github.com/elastic/docs-team/issues/106

File: docs/reference/index.md (hunk 2 above)
Comment (marciw) [reply docs/reference/index.md]: fixed in de9b5e2221b0e2e1eb9e915d7ba6a1c4758cb477

File: docs/reference/index.md [hunk 3]
```diff
@@ -46,37 +45,41 @@ The client’s features include:
...
-## Compatibility [_compatibility]
+## {{es}} version compatibility [_compatibility]
 
-Language clients are _forward compatible:_ each client version works with equivalent and later minor versions of {{es}} without breaking. 
+Language clients are **forward compatible**: each client version works with equivalent and later minor versions of the **same or next major** version of {{es}}. For full compatibility, the client and {{es}} minor versions should match.
 
-Compatibility does not imply full feature parity. New {{es}} features are supported only in equivalent client versions. For example, an 8.12 client fully supports {{es}} 8.12 features and works with 8.13 without breaking; however, it does not support new {{es}} 8.13 features. An 8.13 client fully supports {{es}} 8.13 features.
+| Client version | {{es}} `8.x` | {{es}} `9.x` | {{es}} `10.x` |
+|----------------|---------------------------------|---------------------------------|----------------------------------|
+| 9.x client| &#10060; Not compatible with {{es}} 8.x | &#9989; Compatible with {{es}} 9.x | &#9989; Compatible with {{es}} 10.x |
```
[the remark this answers is not in the document]
Comment (marciw) [reply docs/reference/index.md]: fixed in de9b5e2221b0e2e1eb9e915d7ba6a1c4758cb477

**Review by miguelgrinberg — APPROVED** [review]

**Comment by miguelgrinberg** [comment]
@marciw The lint failure is unrelated, I'll fix that separately.

**Comment by marciw** [comment]
Sigh, I guess I shouldn't have updated my branch before merging... @miguelgrinberg is there anything I can fix here? The integration tests build failed https://buildkite.com/elastic/elasticsearch-py-integration-tests/builds/5686

**Comment by marciw** [comment]
buildkite test this please

File: docs/reference/index.md [hunk 4]
```diff
@@ -46,37 +45,41 @@ The client’s features include:
...
+As of version 8.0, {{es}} offers a [compatibility mode](elasticsearch://reference/elasticsearch/rest-apis/compatibility.md) for smoother upgrades. In compatibility mode, you can upgrade your {{es}} cluster to the next major version while continuing to use your existing client during the transition. 
 
-For example, to upgrade a system that uses {{es}} 8.x you can upgrade the {{es}} server to 9.x first, and the 8.x Python {{es}} client will continue to work (aside from any breaking changes, which should be listed in the server release notes). You can continue using the 8.x client during the server migration, and only upgrade it once the server migration is complete. The process is described in detail in the [REST API compatibility workflow](https://www.elastic.co/docs/reference/elasticsearch/rest-apis/compatibility#_rest_api_compatibility_workflow) section of the {{es}} documentation.
+For example, if you're upgrading {{es}} from 8.x to 9.x, you can continue to use the 8.x Python client during and after the {{es}} server upgrade, with the exception of [breaking changes](../release-notes/breaking-changes.md).
```
Comment (pquentin) [inline docs/reference/index.md:79]: This links to the breaking changes for the Python client, which are irrelevant here since the client remains on 8.x. We need to link to the Elasticsearch release notes instead.
