### PR TITLE
Object support serializing AttrDict. Fixes #3075

### LINKED ISSUE #3075: Object._serialize() missing 1 required positional argument: 'skip_empty'
This started happening with the `9.1.1` release:

```
src/catalog/search/documents.py:59: in save
    return super().save(**kwargs)
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/_sync/document.py:440: in save
    body=self.to_dict(skip_empty=skip_empty),
src/catalog/search/documents.py:79: in to_dict
    doc = super().to_dict(skip_empty=skip_empty)
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/document_base.py:593: in to_dict
    d = super().to_dict(skip_empty=skip_empty)
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/utils.py:606: in to_dict
    v = f.serialize(v, skip_empty=skip_empty)
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/field.py:152: in serialize
    return self._safe_serialize(data, skip_empty)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = Object(), data = {'data': {'abc': 'def'}}, skip_empty = True
    def _safe_serialize(self, data: Any, skip_empty: bool) -> Any:
        try:
            return self._serialize(data, skip_empty)
        except TypeError:
            # older method signature, without skip_empty
>           return self._serialize(data)  # type: ignore[call-arg]
E           TypeError: Object._serialize() missing 1 required positional argument: 'skip_empty'
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/field.py:130: TypeError
```

Everything works fine with `9.1.0`

Thanks.

### PR DESCRIPTION
**Pull request by isra17**
Fixes #3075

Less agressive fix of #3076 

cc @miguelgrinberg

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
This was fixed in https://github.com/elastic/elasticsearch-py/pull/3080. Closing.
