### ISSUE TITLE
Object._serialize() missing 1 required positional argument: 'skip_empty'

### ISSUE THREAD

**Issue by selimt** [elastic/elasticsearch-py#3075]
This started happening with the `9.1.1` release:

```
src/catalog/search/documents.py:59: in save
    return super().save(**kwargs)
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/_sync/document.py:440: in save
    body=self.to_dict(skip_empty=skip_empty),
src/catalog/search/documents.py:79: in to_dict
    doc = super().to_dict(skip_empty=skip_empty)
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/document_base.py:593: in to_dict
    d = super().to_dict(skip_empty=skip_empty)
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/utils.py:606: in to_dict
    v = f.serialize(v, skip_empty=skip_empty)
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/field.py:152: in serialize
    return self._safe_serialize(data, skip_empty)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = Object(), data = {'data': {'abc': 'def'}}, skip_empty = True
    def _safe_serialize(self, data: Any, skip_empty: bool) -> Any:
        try:
            return self._serialize(data, skip_empty)
        except TypeError:
            # older method signature, without skip_empty
>           return self._serialize(data)  # type: ignore[call-arg]
E           TypeError: Object._serialize() missing 1 required positional argument: 'skip_empty'
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/field.py:130: TypeError
```

Everything works fine with `9.1.0`

Thanks.

**Comment by miguelgrinberg** [comment]
Hi, I need more details to fully understand this issue. Could you share the entire stack trace chain to see if that provides more insight?

Also, are you using custom `Field` instances in your application, or is this happening with the standard Elasticsearch fields we provide with this package?

**Comment by selimt** [comment]
Here is the full stderr from the unittest:

```
==================================== ERRORS ====================================
__________ ERROR at setup of TestNamespaces.test_namespace_taggables ___________
self = Object(), data = {'data': {'abc': 'def'}}, skip_empty = True
    def _safe_serialize(self, data: Any, skip_empty: bool) -> Any:
        try:
>           return self._serialize(data, skip_empty)
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/field.py:127: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = Object(), data = {'data': {'abc': 'def'}}, skip_empty = True
    def _serialize(
        self, data: Optional[Union[Dict[str, Any], "InnerDoc"]], skip_empty: bool
    ) -> Optional[Dict[str, Any]]:
        if data is None:
            return None
    
        # somebody assigned raw dict to the field, we should tolerate that
        if isinstance(data, collections.abc.Mapping):
            return data
    
>       return data.to_dict(skip_empty=skip_empty)
E       TypeError: AttrDict.to_dict() got an unexpected keyword argument 'skip_empty'
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/field.py:575: TypeError
During handling of the above exception, another exception occurred:
make_rolodex = <function make_rolodex.<locals>._make_rolodex at 0x7fd09614c4c0>
namespace1 = Namespace(index='catalog-test-namespaces_foo', id='2a4b421b-783f-4a3d-8354-e411322b15e7')
    @pytest.fixture
    def rolodex_t1(make_rolodex, namespace1):
        """Make a rolodex document with namespace1."""
>       return make_rolodex(namespace=namespace1, name="abcd")
tests/catalog_search/conftest.py:590: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/catalog_search/conftest.py:349: in _make_rolodex
    rolodex.save(index=index, validate=False)
src/catalog/utils.py:90: in retry_operation_on_exception_wrapper
    return func(*args, **kwargs)
src/catalog/search/documents.py:59: in save
    return super().save(**kwargs)
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/_sync/document.py:440: in save
    body=self.to_dict(skip_empty=skip_empty),
src/catalog/search/documents.py:79: in to_dict
    doc = super().to_dict(skip_empty=skip_empty)
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/document_base.py:593: in to_dict
    d = super().to_dict(skip_empty=skip_empty)
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/utils.py:606: in to_dict
    v = f.serialize(v, skip_empty=skip_empty)
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/field.py:152: in serialize
    return self._safe_serialize(data, skip_empty)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = Object(), data = {'data': {'abc': 'def'}}, skip_empty = True
    def _safe_serialize(self, data: Any, skip_empty: bool) -> Any:
        try:
            return self._serialize(data, skip_empty)
        except TypeError:
            # older method signature, without skip_empty
>           return self._serialize(data)  # type: ignore[call-arg]
E           TypeError: Object._serialize() missing 1 required positional argument: 'skip_empty'
/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/field.py:130: TypeError
---------------------------- Captured stderr setup -----------------------------
```

We do use custom fields but they are derived from standard fields. Here is the document definition:

```
class CatalogDocument(Document):
    """Parent class to wrap shared functionality between Catalog Documents and Indices."""

    @classmethod
    def delete_index(cls, index):
        """Wrapper around Index delete."""
        return Index(name=index).delete()

    @classmethod
    @retry_operation_on_index_not_found
    def refresh_index(cls, index=None):
        """Wrapper around Index refresh to retry on index_not_found_exceptions."""
        if index is None:
            index = cls.Index.name
        return Index(name=index).refresh()

    @retry_operation_on_exception(
        retry_on_exceptions=(KeyError,),
        raise_on_retry_failure=False,
        retry_failure_return_value=None
    )
    def save(self, **kwargs):
        """Wrapper around Document save to retry on exceptions."""
        return super().save(**kwargs)

    @classmethod
    def update_by_query(cls, index=None, **kwargs):
        """Class method to provide access to the wrapped UpdateByQuery class."""
        if index is None:
            index = cls.Index.name
        return CatalogUpdateByQuery(index=index, **kwargs)

    def to_dict(self, skip_empty=False):
        """Prevent elasticsearch.dsl from stripping empty metadata['data']."""

        # Elasticsearch removes empty dicts, lists, etc. on save.
        # There is a 'skip_empty' option which defaults to True, but setting it to False only
        # affects top level elements. Nested elements such as doc['metadata']['data'] might
        # still be excluded if they are empty, as per this github issue:
        # https://github.com/elastic/elasticsearch-dsl-py/issues/1094
        # This fix is loosely based on:
        # https://github.com/harvard-lil/capstone/pull/1243/files?file-filters%5B%5D=.py#diff-8348f4995c02010d3fc708873c6b81595803a80afd665b3af4ad3bd0da1e741d

        doc = super().to_dict(skip_empty=skip_empty)
        if hasattr(self, 'metadata'):
            if isinstance(self.metadata.data, AttrDict):
                doc['metadata']['data'] = self.metadata.data.to_dict()
            else:
                doc['metadata']['data'] = self.metadata.data.to_dict(skip_empty=skip_empty)
        return doc


class Rolodex(CatalogDocument):
    """The Rolodex ES Index."""

    # Each document class needs to have its own Index class otherwise the mappings are merged.
    # https://elastic.co/docs/reference/elasticsearch/clients/python/dsl_how_to_guides/_document_inheritance
    class Index:
        name = get_catalog_index("rolodex", pattern=True)

    name = SuggesterField()
    primary_namespace_id = Keyword()
    taggable_id = Keyword()
    namespace_id = Keyword()
    connection_id = Keyword()
    taggable_meta = MetadataField()
    namespace_meta = NamespaceMetadataField()
    connection_meta = MetadataField()
    path = PathField()
    accessor = Flattened()
    sync_time = Date()
    namespace_promoted_fields = PromotedFields("namespace_promoted_fields")
    taggable_promoted_fields = PromotedFields("taggable_promoted_fields")
    connection_promoted_fields = PromotedFields("connection_promoted_fields")
```

**Comment by miguelgrinberg** [comment]
Your test is trying to write the value `{'abc': 'def'}` on one of your document fields. The data appears like a dictionary in the stack trace, but I think it must be of a different type, and it just renders in dict format when printed. Can you tell me more about this field and this dict-like value? Or maybe show me the code that sets the field? Thanks!

**Comment by selimt** [comment]
Here is part of the fixture that creates that document:
```
@pytest.fixture
def make_rolodex(es, make_namespace):  # noqa: C901
    """Make a rolodex document."""
    def _make_rolodex(taggable_id=None, name=None, primary_namespace=None, taggable_meta=None,
                      connection_id=None, connection_meta=None, namespace=None, accessor=None,
                      namespace_promoted_fields=None, taggable_promoted_fields=None,
                      connection_promoted_fields=None):
        ...
        if taggable_meta is None:
            taggable_meta = {"abc": "def"}
        ...
        rolodex = Rolodex(namespace_id=namespace.meta.id,
                          path=namespace.path,
                          namespace_meta=namespace.metadata,
                          taggable_id=taggable_id,
                          name=name,
                          primary_namespace=primary_namespace_id,
                          taggable_meta={"data": taggable_meta},
                          connection_id=connection_id,
                          connection_meta={"data": connection_meta},
                          accessor=accessor,
                          namespace_promoted_fields=namespace_promoted_fields,
                          taggable_promoted_fields=taggable_promoted_fields,
                          connection_promoted_fields=connection_promoted_fields
                          )
        rolodex.meta.id = str(connection_id)
        index = get_library_index(index_type="rolodex", library=primary_namespace.path.split(".")[0])
        rolodex.save(index=index, validate=False)
        rolodex_es_refresh()
        return rolodex
    yield _make_rolodex
```

The field `taggable_meta` is a `Flattened` field and is declared in the template as follows:

```

class Flattened(CustomField):
    """Adds ES "flattened" field type support."""

    builtin_type = 'flattened'
```

At the time there wasn't a `Flattened` field type support for elasticsearch_dsl so I had to support it like this.

**Comment by selimt** [comment]
Looks like it was added to `elasticsearch/dsl/field.py` but not to `elasticsearch/dsl/__init__.py`

**Comment by selimt** [comment]
Unfortunately the test is still failing with the same error even after I moved to using `elasticsearch.dsl.field.Flattened`

**Comment by selimt** [comment]
I misspoke. The `taggable_meta` field is defined as follows:

```
class MetadataField:
    """Configure "metadata" fields."""

    CatalogBooleanField = Boolean
    CatalogDateField = Date
    CatalogFlattenedField = Flattened
    CatalogTextField = Text
    CatalogObjectField = Object

    def __new__(cls):
        """Return the composite metadata field definition."""

        return cls.CatalogObjectField(
            properties={
                "data": cls.CatalogFlattenedField(),
                "_system": cls.CatalogObjectField(
                    properties={
                        "created": cls.CatalogDateField(default_timezone="+0"),
                        "updated": cls.CatalogDateField(default_timezone="+0"),
                        "created_by": cls.CatalogTextField(fielddata=True),
                        "updated_by": cls.CatalogTextField(fielddata=True),
                        "latest": cls.CatalogBooleanField()
                    }
                )
            }
        )
```

The `data` subfield is the Flattened type.

**Comment by selimt** [comment]
Figured out what the issue is. The pytest fixture was populating the field like this:
```
namespace_meta=namespace.metadata,
```

instead of like this:

```
namespace_meta={"data": namespace.metadata},
```

After I made the change, the error went away.

**Comment by selimt** [comment]
In addition, I had to make the following change:
```
            namespace_promoted_fields = []
            for pf in namespace.promoted_fields:
                pf = pf.to_dict()
                namespace_promoted_fields.append(pf)

```
It looks like nested documents are stored as `AttrDict` objects and I can't pass that as a list of AttrDict objects directly to the document constructor.

**Comment by gioboa** [comment]
Hi, can you create a basic reproduction repository to highlight this issue please?

**Comment by miguelgrinberg** [comment]
Okay, there is a lot to process here, but there are at least a couple of action items for me here:

1. Expose `Flattened` in the top-level package (will also check if we missed any other recently added field types)
2. Allow passing of nested documents as `AttrDict` instances

Also you seem to have implemented a workaround for a bug we had for a long time related to the `skip_empty` flag in the `to_dict()` method. We have actually addressed this bug in the most recent patch releases of 8.19, 9.0 and 9.1, so you may be able to simplify your solution now that `skip_empty` works in nested objects. In fact I think the fix for this issue in 9.1.1 indirectly have caused this whole problem for your application.

Aside from this, it is unclear if there are any other bugs or issues that I can address. You seem to be using a heavily customized solution, so it is hard for me to tell. For example, I do not understand how you have a field of a custom type `MetadataField` in your index, but the definition of this class does not show `CustomField` as a parent class, and in fact, this is a class with no parents at all. Have you implemented the entire public API of `Field` in your class?

**Comment by selimt** [comment]
Hi Miguel, thank you for your response.

I wasn’t aware that all composite fields needed to inherit from CustomField. When we started working on this project, our goal was to create a template using the abstract field classes provided by elasticsearch_dsl (now elasticsearch.dsl) .

If there is a benefit to using CustomField as the base class,  I can definitely change those.

@gioboa I can certainly try to provide a code snippet that shows the issue with the nested documents.

And thanks for letting us know that we don’t need the workaround for the to_dict() method anymore.

**Comment by miguelgrinberg** [comment]
> I wasn’t aware that all composite fields needed to inherit from CustomField.
> If there is a benefit to using CustomField as the base class, I can definitely change those.

"needed" is a strong word here. We do not enforce the class hierarchy, but there is an assumption (at least from my part) that all fields in an index are represented by subclasses of the `Field` base class. Also nested fields are assumed to be instances of `Nested`, with a value that is an instance of an `InnerDoc` subclass.

To support custom needs we provide `CustomField` as a base class for your custom fields. See [this example](https://github.com/elastic/elasticsearch-py/blob/3d47b77c71de8218689e36566c4023b758482a0b/test_elasticsearch/test_dsl/_sync/test_document.py#L101-L110) of a custom field in our test suite. Note that it does not need to implement much logic, because most of it is inherited.

The `skip_empty` bug fix was a bit tricky, and I had made the assumption that all fields have the well known behaviors of the `Field` base class. Your application broke after this fix because some these assumptions aren't true in your case.

**Comment by selimt** [comment]
I understand. We are in fact inheriting from the `Field` class. If you notice, we are using the `__new__` method to construct the composite field and returning an `Object` class:

```python
class MetadataField:
    """Configure "metadata" fields."""

    CatalogBooleanField = Boolean
    CatalogDateField = Date
    CatalogFlattenedField = Flattened
    CatalogTextField = Text
    CatalogObjectField = Object

    def __new__(cls):
        """Return the composite metadata field definition."""

        return cls.CatalogObjectField(
            properties={
                "data": cls.CatalogFlattenedField(),
                "_system": cls.CatalogObjectField(
                    properties={
                        "created": cls.CatalogDateField(default_timezone="+0"),
                        "updated": cls.CatalogDateField(default_timezone="+0"),
                        "created_by": cls.CatalogTextField(fielddata=True),
                        "updated_by": cls.CatalogTextField(fielddata=True),
                        "latest": cls.CatalogBooleanField()
                    }
                )
            }
        )
```

The reason we are doing this is because we needed to share the field definitions with another package called django-elasticsearch-dsl where the same definition needs to be shared like this:

```python
from django_elasticsearch_dsl import (
    BooleanField,
    DateField,
    DEDField,
    IntegerField,
    ObjectField
)
from django_elasticsearch_dsl_drf.compat import StringField
from elasticsearch.dsl.field import Flattened

class FlattenedField(DEDField, Flattened):
    """Catalog Flattened Field."""

class MetadataField(catalog.search.template.MetadataField):
    """Catalog metadata field."""

    CatalogBooleanField = BooleanField
    CatalogObjectField = ObjectField
    CatalogTextField = StringField
    CatalogDateField = DateField
    CatalogFlattenedField = FlattenedField
```

This way we don't have to repeat the same template definition between the pure elasticsearch.dsl based workers and the Django part.

**Comment by miguelgrinberg** [comment]
@selimt Okay, so this wasn't as strange as I initially thought, I missed the `__new__` that you have in your class.

After reviewing everything again I think you have identified the issue correctly. You were assigning `AttrDict` instances to one or more of your custom types, which I think was not intended. This is something that my recent fix for `skip_empty` does not expect.

I'll make sure that `AttrDict` is treated like a regular dict when it is assigned to a field.

> This way we don't have to repeat the same template definition between the pure elasticsearch.dsl based workers and the Django part.

I haven't used the Django wrapper so I may be wrong, but if they offer subclasses of our `Field` classes, maybe you can use their subclasses even for the non-Django parts? It doesn't sound great that you have to have field classes for Django and non-Django code.

**Comment by selimt** [comment]
@gioboa , here is a simple repro:

```python
from elasticsearch.dsl.connections import connections

connections.create_connection("default", hosts=[{"host": "localhost", "port": 9200, "scheme":"http"}])

from elasticsearch.dsl import Document, Nested, Text, Integer, InnerDoc

class Comment(InnerDoc):
  name = Text()
  num = Integer()


class MyDoc(Document):
  nested = Nested(Comment)  
  
class MyDoc2(Document):
  nested_fields = Nested(Comment)


doc = MyDoc(nested_fields=[{"name": "hello", "num": 1}, {"name": "world", "num": 2}])

doc.save(index="test-index", validate=False)

doc2 = MyDoc2(nested_fields=doc.nested_fields)

doc2.save(index="test-index2", validate=False)
```

It looks like if `validate` is False, then it causes this error:

```
Traceback (most recent call last):
  File "/var/tmp/doNotRemove/venvs/es_migration/lib64/python3.11/site-packages/elasticsearch/dsl/field.py", line 127, in _safe_serialize
    return self._serialize(data, skip_empty)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/doNotRemove/venvs/es_migration/lib64/python3.11/site-packages/elasticsearch/dsl/field.py", line 575, in _serialize
    return data.to_dict(skip_empty=skip_empty)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AttrDict.to_dict() got an unexpected keyword argument 'skip_empty'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lucas/ilm/home/stuvi/work/catalog/./test_nested.py", line 25, in <module>
    doc2.save(index="test-index2", validate=False)
  File "/var/tmp/doNotRemove/venvs/es_migration/lib64/python3.11/site-packages/elasticsearch/dsl/_sync/document.py", line 440, in save
    body=self.to_dict(skip_empty=skip_empty),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/doNotRemove/venvs/es_migration/lib64/python3.11/site-packages/elasticsearch/dsl/document_base.py", line 593, in to_dict
    d = super().to_dict(skip_empty=skip_empty)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/doNotRemove/venvs/es_migration/lib64/python3.11/site-packages/elasticsearch/dsl/utils.py", line 606, in to_dict
    v = f.serialize(v, skip_empty=skip_empty)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/doNotRemove/venvs/es_migration/lib64/python3.11/site-packages/elasticsearch/dsl/field.py", line 145, in serialize
    return list(
           ^^^^^
  File "/var/tmp/doNotRemove/venvs/es_migration/lib64/python3.11/site-packages/elasticsearch/dsl/field.py", line 130, in _safe_serialize
    return self._serialize(data)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: Object._serialize() missing 1 required positional argument: 'skip_empty'
```

**Comment by leameow** [comment]
We have a similar issue, with the exact same backtrace:

```
self = Object()
data = {'name': 'latest', 'repository_name': ...}
skip_empty = True

    def _serialize(
        self, data: Optional[Union[Dict[str, Any], "InnerDoc"]], skip_empty: bool
    ) -> Optional[Dict[str, Any]]:
        if data is None:
            return None

        # somebody assigned raw dict to the field, we should tolerate that
        if isinstance(data, collections.abc.Mapping):
            return data

>       return data.to_dict(skip_empty=skip_empty)
E       TypeError: AttrDict.to_dict() got an unexpected keyword argument 'skip_empty'

.../venv/lib/python3.13/site-packages/elasticsearch/dsl/field.py:575: TypeError
```

To be fair, `AttrDict` not being a `Mapping` has been an issue multiple time in the past in our own codebase :/ 

Any reason `AttrDict` is not implementing `MutableMapping` and `AttrList` a `MutableSequence`?

Fwiw we don't use `validate=False`.

**Comment by leameow** [comment]
In our case it seems to be triggered by some of our custom merging logic, where we take the values of existing documents (`AttrDict`) and set them in a new document.

**Comment by miguelgrinberg** [comment]
@selimt Why are you saving your objects with the `validate=False` flag? Is there any issue that occurs when using the default of validating the fields? Because that is the process that checks the fields and adresses minor inconsistencies, such as the one you have here, where a field that is supposed to be an `InnerDoc` was given an AttriDict value instead.

I cannot reproduce the original you reported issue unless I disable validation like you are.

**Comment by selimt** [comment]
If I don't set `validate=False` I get the following error:

```
[2025-09-18 21:26:25,325: ERROR/ForkPoolWorker-16] Task sync_namespace[8cc53379-d321-4b39-af34-80a509a1fb13] raised unexpected: UnpickleableExceptionWrapper('elasticsearch', 'BadRequestError', ('document_parsing_exception',), "BadRequestError('document_parsing_exception', meta=ApiResponseMeta(status=400, http_version='1.1', headers={'X-elastic-product': 'Elasticsearch', 'content-type': 'application/vnd.elasticsearch+json;compatible-with=9', 'content-length': '466'}, duration=0.09662246704101562, node=NodeConfig(scheme='http', host='search', port=9200, path_prefix='', headers={'user-agent': 'elasticsearch-py/9.1.1 (Python/3.10.14; elastic-transport/9.1.0)'}, connections_per_node=10, request_timeout=10.0, http_compress=False, verify_certs=True, ca_certs=None, client_cert=None, client_key=None, ssl_assert_hostname=None, ssl_assert_fingerprint=None, ssl_version=None, ssl_context=None, ssl_show_warn=True, _extras={})), body={'error': {'root_cause': [{'type': 'parsing_exception', 'reason': 'failed to parse [value_num]: expected text or object, but got VALUE_NUMBER', 'line': 1, 'col': 843}], 'type': 'document_parsing_exception', 'reason': '[1:843] failed to parse: failed to parse [value_num]: expected text or object, but got VALUE_NUMBER', 'caused_by': {'type': 'parsing_exception', 'reason': 'failed to parse [value_num]: expected text or object, but got VALUE_NUMBER', 'line': 1, 'col': 843}}, 'status': 400})")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/src/catalog/tasks/sync/tasks.py", line 52, in sync_namespace
    namespace.save(index=namespaces_index, skip_empty=False)
  File "/app/src/catalog/utils.py", line 90, in retry_operation_on_exception_wrapper
    return func(*args, **kwargs)
  File "/app/src/catalog/search/documents.py", line 53, in save
    return super().save(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/dsl/_sync/document.py", line 438, in save
    meta = es.index(
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 415, in wrapped
    return api(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/_sync/client/__init__.py", line 2940, in index
    return self.perform_request(  # type: ignore[return-value]
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 271, in perform_request
    response = self._perform_request(
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 351, in _perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
celery.utils.serialization.UnpickleableExceptionWrapper: BadRequestError('document_parsing_exception', meta=ApiResponseMeta(status=400, http_version='1.1', headers={'X-elastic-product': 'Elasticsearch', 'content-type': 'application/vnd.elasticsearch+json;compatible-with=9', 'content-length': '466'}, duration=0.09662246704101562, node=NodeConfig(scheme='http', host='search', port=9200, path_prefix='', headers={'user-agent': 'elasticsearch-py/9.1.1 (Python/3.10.14; elastic-transport/9.1.0)'}, connections_per_node=10, request_timeout=10.0, http_compress=False, verify_certs=True, ca_certs=None, client_cert=None, client_key=None, ssl_assert_hostname=None, ssl_assert_fingerprint=None, ssl_version=None, ssl_context=None, ssl_show_warn=True, _extras={})), body={'error': {'root_cause': [{'type': 'parsing_exception', 'reason': 'failed to parse [value_num]: expected text or object, but got VALUE_NUMBER', 'line': 1, 'col': 843}], 'type': 'document_parsing_exception', 'reason': '[1:843] failed to parse: failed to parse [value_num]: expected text or object, but got VALUE_NUMBER', 'caused_by': {'type': 'parsing_exception', 'reason': 'failed to parse [value_num]: expected text or object, but got VALUE_NUMBER', 'line': 1, 'col': 843}}, 'status': 400})
```

The document I am trying to save is this:

```
{'path': 'lib_foo', 'metadata': {'data': {'no_promote': {'foo': 'bar'}}, '_system': {'created': '2025-09-18T21:26:25.113558+00:00', 'created_by': '_peautomaton'}}, 'sync_time': '2025-09-18T21:26:25.221722+00:00', 'promoted_fields': [{'name': 'def.bar_num', 'value_num': '123'}, {'name': 'abc.que.foo_date', 'value_date': '2025-09-18T21:26:25.108000+00:00'}]}
```

Here is my mapping for the `promoted_fields` nested type:

```
              "promoted_fields": {
                "type": "nested",
                "properties": {
                  "value_str": {
                    "fielddata": true,
                    "analyzer": "keyword",
                    "fields": {
                      "suggest": {
                        "analyzer": "completion",
                        "contexts": [
                          {
                            "path": "promoted_fields.name",
                            "name": "name",
                            "type": "category"
                          }
                        ],
                        "type": "completion"
                      }
                    },
                    "type": "text"
                  },
                  "name": {
                    "type": "text"
                  },
                  "value_num": {
                    "fields": {
                      "suggest": {
                        "analyzer": "completion",
                        "contexts": [
                          {
                            "path": "promoted_fields.name",
                            "name": "name",
                            "type": "category"
                          }
                        ],
                        "type": "completion"
                      }
                    },
                    "type": "integer"
                  },
                  "value_vector_512": {
                    "dims": 512,
                    "similarity": "cosine",
                    "type": "dense_vector"
                  },
                  "value_date": {
                    "fields": {
                      "suggest": {
                        "analyzer": "completion",
                        "contexts": [
                          {
                            "path": "promoted_fields.name",
                            "name": "name",
                            "type": "category"
                          }
                        ],
                        "type": "completion"
                      }
                    },
                    "type": "date"
                  }
                }
              }
```

**Comment by selimt** [comment]
To clarify, the nested doc has multiple "value" fields but for each nested doc, only one of those value fields are populated. I believe when `validate` is `True` the validation logic tries to fill in those unset values and elasticsearch doesn't like the default value set by validation.
